### ISSUE TITLE
Booleans won't be displayed

### ISSUE THREAD

**Issue by smogg** [RackSec/wilson#8]
Solution: apply `str`?

**Comment by lvh** [comment]
Create a test; then figure out what you want the test to do :) Maybe the display fn should be configurable too; with a nice default that e.g. pr-str's stuff, capitalizes stuff, &c.

**Comment by smogg** [comment]
Now I actually wonder if this should be solved in Wilson in the first place - maybe it should be user's responsibility to pass the right thing so it's not a bug after all?

**Comment by lvh** [comment]
That's an interesting question: if we do it for bools, how many data types do we do it for. It's certainly different from e.g. row->attrs because you pretty much need that in order to produce the correct reagent DOM structure (you can modify the result you get but that implies you know what the DOM looks like). It seems like a reasonable enough thing for Wilson to solve because it feels like a reasonably common problem; but I agree that it's different from some of the other customizations :)
